import AuthProvider from "../utils/providers/auth/AuthProvider";
import { Roboto } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/utils/providers/query/QueryProvider";
import Script from "next/script";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
});

export const metadata = {
  title: "uTalkTo",
  description: "Generated by webDev2776",
};

export default function RootLayout({ children }) {
  return (
    <>
      {/* Google Analytics */}
      <Script
        strategy="afterInteractive"
        src={`https://www.googletagmanager.com/gtag/js?id=G-TN1GYE9DZ3`}
      />
      <Script id="google-analytics" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-TN1GYE9DZ3');
        `}
      </Script>
      <html lang="en">
        <AuthProvider>
          <body
            className={`${roboto.className} bg-gradient-to-b from-oxford via-cambridge to-bittersweet min-h-screen`}
          >
            <div>
              <QueryProvider>{children}</QueryProvider>
            </div>
          </body>
        </AuthProvider>
      </html>
    </>
  );
}
